### ISSUE TITLE
 returned non-zero exit status 1

### ISSUE THREAD

**Issue by tomtao2022** [Jekso/AndroidTV-Remote-Controller#2]
Starting ADB server...

😎 ADB server is started.

💡 Connecting to 192.168.31.68 ...

💡 Getting connected devices...

💡 There are 1 connected devices.

😎 Device: 192.168.31.68:5555 is connected successfully.

😎 Device: 192.168.31.68 is connected.

['adb', '-s', '192.168.31.68:5555', 'shell', 'input', 'keyevent', 'KEYCODE_VOLUME_UP']

 File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['adb', '-s', '192.168.31.68:5555', 'shell', 'input', 'keyevent', 'KEYCODE_VOLUME_UP']' returned non-zero exit status 1.

**Comment by Jekso** [comment]
Can you use this command in external terminal and give me the result
``
**`adb -s '192.168.31.68:5555' shell input keyevent 'KEYCODE_VOLUME_UP`**'

**Comment by tomtao2022** [comment]
Found reason Device is not open adb debug mode

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
